# ----------------------------------------------------
# This file is generated by the Qt Visual Studio Tools.
# ------------------------------------------------------

QT += core gui widgets
TEMPLATE = app
TARGET = QStegano
DESTDIR = ./Debug
CONFIG += debug
LIBS += -L"."
DEPENDPATH += .
INCLUDEPATH += ./3rdparty/include
MOC_DIR += debug
OBJECTS_DIR += debug
UI_DIR += debug
RCC_DIR += debug
include(QStegano.pri)
